/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mau.screens;

import br.com.mau.model.Agenda;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import br.com.mau.dao.impl.GenericDAO;
import br.com.mau.controller.PersistenceController;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.text.MaskFormatter;
import br.com.mau.util.Agendamento;
import javax.swing.JOptionPane;

/**
 *
 * @author Mauricio
 */
public class JIFAgendamento extends javax.swing.JInternalFrame {

    private static org.apache.log4j.Logger log = org.apache.log4j.Logger.getLogger(JIFAgendamento.class);

    /**
     * Creates new form JIFAgendamento
     */
    public JIFAgendamento() {
        try {
            initComponents();
            persistence = new PersistenceController();
            persistence.loadPersistenceContext();
            MaskFormatter formatter = new MaskFormatter("##/##/####");
            formatter.setPlaceholderCharacter('_');

            formattedTextField = new JFormattedTextField(formatter);

        } catch (ParseException ex) {
            Logger.getLogger(JIFAgendamento.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelAgendamento = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Date date = new Date();
        SpinnerDateModel sm = new SpinnerDateModel(date, null, null, Calendar.HOUR_OF_DAY);
        jspinnerInicial = new javax.swing.JSpinner(sm);
        Date dateFinal = new Date();
        SpinnerDateModel sm2 = new SpinnerDateModel(dateFinal, null, null, Calendar.HOUR_OF_DAY);
        jspinnerTermino = new javax.swing.JSpinner(sm2);
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlcodigo = new javax.swing.JLabel();
        jbSalvar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        panelTarefaBasica = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescricao = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        labelStatus = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Agendamento");

        panelAgendamento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agendamento", 0, 0, null, java.awt.Color.blue));

        jLabel1.setText("Hora inicial:");

        jLabel3.setText("Hora término:");

        JSpinner.DateEditor de = new JSpinner.DateEditor(jspinnerInicial, "HH:mm:ss");
        jspinnerInicial.setEditor(de);

        JSpinner.DateEditor de2 = new JSpinner.DateEditor(jspinnerTermino, "HH:mm:ss");
        jspinnerTermino.setEditor(de2);

        jLabel7.setText("Data:");

        jLabel8.setText("codigo#:");

        javax.swing.GroupLayout panelAgendamentoLayout = new javax.swing.GroupLayout(panelAgendamento);
        panelAgendamento.setLayout(panelAgendamentoLayout);
        panelAgendamentoLayout.setHorizontalGroup(
            panelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgendamentoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addGroup(panelAgendamentoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jspinnerInicial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                        .addComponent(jspinnerTermino, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jlcodigo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAgendamentoLayout.setVerticalGroup(
            panelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgendamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jspinnerInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jspinnerTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jlcodigo))
                .addGap(36, 36, 36)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jbSalvar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbCancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        panelTarefaBasica.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tarefa Básica", 0, 0, null, new java.awt.Color(51, 102, 255)));

        jLabel4.setText("Nome:");

        jLabel5.setText("Descrição: ");

        taDescricao.setColumns(20);
        taDescricao.setRows(5);
        jScrollPane1.setViewportView(taDescricao);

        jLabel6.setText("Use este assistente para agendar o inicio e o termino do processo de irrigação.");

        javax.swing.GroupLayout panelTarefaBasicaLayout = new javax.swing.GroupLayout(panelTarefaBasica);
        panelTarefaBasica.setLayout(panelTarefaBasicaLayout);
        panelTarefaBasicaLayout.setHorizontalGroup(
            panelTarefaBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTarefaBasicaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTarefaBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTarefaBasicaLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(26, 26, 26)
                        .addComponent(tfNome))
                    .addGroup(panelTarefaBasicaLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 177, Short.MAX_VALUE))
                    .addGroup(panelTarefaBasicaLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        panelTarefaBasicaLayout.setVerticalGroup(
            panelTarefaBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTarefaBasicaLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTarefaBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTarefaBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelStatus.setFont(new java.awt.Font("Times New Roman", 3, 8)); // NOI18N
        labelStatus.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAgendamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTarefaBasica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbCancelar, jbSalvar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTarefaBasica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelStatus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbCancelar, jbSalvar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        Agenda agenda = getAgenda();

        if (agenda != null) {
            persistAgenda(agenda);
            registerAgenda(agenda);
            dispose();
        } else {
            labelStatus.setText("** É necessario preencher todos os campos");
            log.error("Não foi possivel salvar agendamento - alguns valores estão nulos");
        }

    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JLabel jlcodigo;
    private javax.swing.JSpinner jspinnerInicial;
    private javax.swing.JSpinner jspinnerTermino;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JPanel panelAgendamento;
    private javax.swing.JPanel panelTarefaBasica;
    private javax.swing.JTextArea taDescricao;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
    private PersistenceController persistence;
    private JFormattedTextField formattedTextField;

    public Agenda loadAgendaFromPanel() {
        
       Long id = null;
        try {
            if(!jlcodigo.getText().isEmpty()) {
                id = Long.parseLong(jlcodigo.getText());
            }
        } catch (NumberFormatException e) {
            throw new RuntimeException("Erro durante a conversão do label codigo# (Long).\n");
        }
        
        String nome = null;

        if (!tfNome.getText().trim().isEmpty()) {
            nome = tfNome.getText().trim();
        }

        String descricao = null;

        if (!taDescricao.getText().trim().isEmpty()) {
            descricao = taDescricao.getText().trim();
        }

        Date data = null;

        if (jDateChooser.getDate() != null) {
            data = jDateChooser.getDate();
        }

        SpinnerDateModel dateModelInicial = (SpinnerDateModel) jspinnerInicial.getModel();
        Date inicialDate = dateModelInicial.getDate();
        Calendar inicial = Calendar.getInstance();
        inicial.setTime(inicialDate);

        SpinnerDateModel dateModelTermino = (SpinnerDateModel) jspinnerTermino.getModel();
        Date terminoDate = dateModelTermino.getDate();
        Calendar termino = Calendar.getInstance();
        termino.setTime(terminoDate);

        if (nome == null || data == null) {
            return null;
        }
        return new Agenda(id, nome, descricao, data, inicial.getTime(), termino.getTime());
    }

    public Agenda getAgenda() {
        return loadAgendaFromPanel();
    }

    private void persistAgenda(Agenda agenda) {
        GenericDAO dao = new GenericDAO(persistence.getPersistenceContext(), Agenda.class);
        
        if(agenda.getId()!= null){
            dao.update(agenda);
           JOptionPane.showMessageDialog(null, "Agenda Atualizada!!","Atualização",
           JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            dao.save(agenda);
            JOptionPane.showMessageDialog(null, "Cadastrado no Banco!!","Cadastro Efetuado",
            JOptionPane.INFORMATION_MESSAGE);
        }        
        dispose();
        dao.close();                
    }

    private void registerAgenda(Agenda agenda) {
        Agendamento agendamento = new Agendamento();
        System.out.println("Qtde: " + agendamento.getJobGroupNames().size());
        agendamento.escalonarAgenda(agenda);
    }

    public void setAgenda(Agenda agenda) {
        resetForm();
        if (agenda != null) {
            populaAgenda(agenda);
        }
    }

    private void resetForm() {
        tfNome.setText("");
        taDescricao.setText("");
        jDateChooser.setDate(null);
    }

    private void populaAgenda(Agenda agenda) {
        jlcodigo.setText(String.valueOf(agenda.getId()));
        tfNome.setText(agenda.getNome());
        taDescricao.setText(agenda.getDescricao());
        jDateChooser.setDate(agenda.getAgenda());

        SpinnerDateModel sm = new SpinnerDateModel(agenda.getHora_inicio(), null, null, Calendar.HOUR_OF_DAY);
        jspinnerInicial = new javax.swing.JSpinner(sm);
        JSpinner.DateEditor de = new JSpinner.DateEditor(jspinnerInicial, "HH:mm:ss");
        jspinnerInicial.setEditor(de);
        
        sm = new SpinnerDateModel(agenda.getHora_fim(), null, null, Calendar.HOUR_OF_DAY);
        jspinnerTermino = new javax.swing.JSpinner(sm);
        de = new JSpinner.DateEditor(jspinnerTermino, "HH:mm:ss");
        jspinnerTermino.setEditor(de);                

    }
}
