/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mau.screens;

import br.com.mau.communication.BluetoothCommunicator;
import gnu.io.CommPortIdentifier;
import gnu.io.SerialPort;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**     
 *
 * @author Mauricio
 */
public class JIFConnection extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFConnection
     */
    public JIFConnection() {
        initComponents();
        communicator = new BluetoothCommunicator();
        btStop.setEnabled(false);
        loadPorts();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelConfig = new javax.swing.JPanel();
        labelImageStatus = new javax.swing.JLabel();
        cbPortas = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfRate = new javax.swing.JTextField();
        btStart = new javax.swing.JButton();
        btStop = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        labelStatus = new javax.swing.JLabel();

        setBackground(java.awt.Color.white);
        setClosable(true);
        setIconifiable(true);
        setTitle("Connection");

        panelConfig.setBackground(java.awt.Color.white);
        panelConfig.setBorder(javax.swing.BorderFactory.createTitledBorder("config"));

        labelImageStatus.setBackground(new java.awt.Color(255, 255, 255));
        labelImageStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/images/no_connected.png"))); // NOI18N

        cbPortas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPortasActionPerformed(evt);
            }
        });

        jLabel2.setText("Porta:");

        jLabel3.setText("Rate:");

        btStart.setText("START");
        btStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStartActionPerformed(evt);
            }
        });

        btStop.setText("STOP");
        btStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStopActionPerformed(evt);
            }
        });

        jLabel5.setText("Status:");

        labelStatus.setText("ok");

        javax.swing.GroupLayout panelConfigLayout = new javax.swing.GroupLayout(panelConfig);
        panelConfig.setLayout(panelConfigLayout);
        panelConfigLayout.setHorizontalGroup(
            panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConfigLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(labelImageStatus)
                .addGap(59, 59, 59)
                .addGroup(panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfRate, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPortas, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btStop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btStart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        panelConfigLayout.setVerticalGroup(
            panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConfigLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelImageStatus)
                    .addGroup(panelConfigLayout.createSequentialGroup()
                        .addGroup(panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(labelStatus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btStart)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbPortas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(btStop))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelConfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelConfig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStopActionPerformed
        if(communicator != null){
            communicator.close();
        }
    }//GEN-LAST:event_btStopActionPerformed

    private void cbPortasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPortasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPortasActionPerformed

    private void btStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStartActionPerformed
//        showImageStatusConnection();
        Object[] params = loadConnectionPane();        
        
        if (params != null){            
            
            Integer index = (Integer)params[2];
            
            if(index != -1){
                Integer rate = (Integer)params[1];
                communicator.connect(portas.get(index), rate);
                labelStatus.setText("established connection!!");
                btStop.setEnabled(true);
                btStart.setEnabled(false);
            }            
        }
        else{
            labelStatus.setText("Error: Confira os valores!!");
        }
    }//GEN-LAST:event_btStartActionPerformed

    private void loadPorts(){
        communicator.initialize();
        portas = communicator.getPorts();
        
        if(!portas.isEmpty()){
            for (CommPortIdentifier portId : portas){
                cbPortas.addItem(portId.getName());                
            }
            labelStatus.setText("Comunicação Serial autorizada!!");
        }
        else{
            labelStatus.setText("Nenhuma porta identificada!!");
        }
        
    }
    
    private void showImageStatusConnection(){
        String[] images = {"error.png","idle.png","offline.png","rx.png","tx.png","txrx.png"};
        
        for (int i = 0; i < 4; i++) {
            labelImageStatus.setIcon(new ImageIcon(getClass().getResource("/br/images/status_"+images[3])));
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(JIFConnection.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.println("Ok");
            labelImageStatus.setIcon(new ImageIcon(getClass().getResource("/br/images/status_"+images[4])));
        }
        labelImageStatus.setIcon(new ImageIcon(getClass().getResource("/br/images/status_"+images[5])));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btStart;
    private javax.swing.JButton btStop;
    private javax.swing.JComboBox cbPortas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelImageStatus;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JPanel panelConfig;
    private javax.swing.JTextField tfRate;
    // End of variables declaration//GEN-END:variables
    private BluetoothCommunicator communicator;
    private ArrayList<CommPortIdentifier> portas;

    private Object[] loadConnectionPane() {
        String portaName = (String) cbPortas.getSelectedItem();
        int index = cbPortas.getSelectedIndex();
        Integer rate = null;
        
        if(!tfRate.getText().trim().isEmpty()){
            rate = Integer.parseInt(tfRate.getText().trim());
        }
        
        Object[] parametros = {portaName,rate,index};
        
        if(portaName != null && rate!=null){
            return parametros;
        }
        return null;        
    }
}
