/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mau.screens;

import br.com.mau.dao.impl.GenericDAO;
import br.com.mau.model.Cultura;
import br.com.mau.tablemodel.CulturaTableModel;
import br.com.mau.util.JPAUtil;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Mauricio
 */
public class JIFGestaoCultura extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFGestaoCultura
     */
    public JIFGestaoCultura() {
        initComponents();
        listenerTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCultura = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtCultura = new javax.swing.JTable();
        jbNovo = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbFechar = new javax.swing.JButton();
        jbPesquisar = new javax.swing.JButton();
        tfPesquisar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Cultura");

        jtCultura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Descrição", "Categoria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtCultura);

        jbNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/images/disk.png"))); // NOI18N
        jbNovo.setText("Novo");
        jbNovo.setOpaque(false);
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/images/alter.png"))); // NOI18N
        jbEditar.setText("Editar");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/images/trash.png"))); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/images/cancel.png"))); // NOI18N
        jbFechar.setText("Fechar");
        jbFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFecharActionPerformed(evt);
            }
        });

        jbPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/images/user.png"))); // NOI18N
        jbPesquisar.setText("Pesquisar");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Pesquisar:");

        javax.swing.GroupLayout jpCulturaLayout = new javax.swing.GroupLayout(jpCultura);
        jpCultura.setLayout(jpCulturaLayout);
        jpCulturaLayout.setHorizontalGroup(
            jpCulturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jpCulturaLayout.createSequentialGroup()
                .addComponent(jbNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbFechar)
                .addGap(0, 75, Short.MAX_VALUE))
            .addGroup(jpCulturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPesquisar))
        );

        jpCulturaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbEditar, jbExcluir, jbFechar, jbNovo, jbPesquisar});

        jpCulturaLayout.setVerticalGroup(
            jpCulturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCulturaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCulturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jpCulturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbEditar)
                    .addComponent(jbExcluir)
                    .addComponent(jbPesquisar)
                    .addComponent(jbFechar))
                .addGap(34, 34, 34))
        );

        jpCulturaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbEditar, jbExcluir, jbFechar, jbNovo, jbPesquisar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpCultura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpCultura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        //Referência para InternlFrame que será exibido
        JIFCultura cultura = new JIFCultura();
        //obter referência do JDesktopPane e adicionar o segundo InternalFrame
        getParent().add(cultura);
        //Configurar visibilidade
        cultura.setVisible(true);
        
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
        
        String pesquisaText = tfPesquisar.getText().trim();
        ArrayList<Cultura> culturas = null;
        
        try {
            
        if(!pesquisaText.isEmpty()){
        culturas = FindCultureAtBase(pesquisaText);
        }
        else{        
            culturas = findAllCultures();
        }                    
            CulturaTableModel tm = new CulturaTableModel(culturas);            
            jtCultura.setModel(tm);        
        
        } catch (Exception e) {
            
            e.printStackTrace();
            
        }
    }//GEN-LAST:event_jbPesquisarActionPerformed

    private void jbFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFecharActionPerformed
        dispose();
    }//GEN-LAST:event_jbFecharActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        
        GenericDAO dao = new GenericDAO(JPAUtil.createEntityManager(), Cultura.class);
        Cultura c = getSelectedCultura();
        if(c == null){
            JOptionPane.showMessageDialog(null, "Selecione uma linha!!");
        }
        else{
            int resp = JOptionPane.showConfirmDialog(null, "Deseja realmente Excluir?", "Exclusão",
                    JOptionPane.YES_NO_OPTION);

            if(resp == JOptionPane.YES_OPTION){
                dao.delete(c.getId());
            }
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        
        Cultura c = getSelectedCultura();
        
        if(c == null){
            JOptionPane.showMessageDialog(null, "Selecione uma linha!!");
        }
        else{
            show(c);
        }
        
    }//GEN-LAST:event_jbEditarActionPerformed

    
    private ArrayList<Cultura> FindCultureAtBase(String nome){
        GenericDAO dao = new GenericDAO(JPAUtil.createEntityManager(), Cultura.class);
        return (ArrayList<Cultura>) dao.findByName(nome);
        
    }
    
    private ArrayList<Cultura> findAllCultures(){
        GenericDAO dao = new GenericDAO(JPAUtil.createEntityManager(), Cultura.class);
        return (ArrayList<Cultura>) dao.findAll();
    }
    
    public JTable getTable(){
        return jtCultura;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbFechar;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JPanel jpCultura;
    private javax.swing.JTable jtCultura;
    private javax.swing.JTextField tfPesquisar;
    // End of variables declaration//GEN-END:variables

    private void listenerTable() {
        getTable().addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                if(e.getClickCount() == 2){                                          
                    Cultura c = getSelectedCultura();
                    if(c != null){
                        show(c);
                    }                    
                }
            }
            
        });
    }
    
    public Cultura getSelectedCultura(){
        int line = getTable().getSelectedRow();
        if(line != -1){
            return ((CulturaTableModel)getTable().getModel()).getCulturaAt(line);
        }
        return null;
    }
    
    public void show(Cultura c){
        JIFCultura frame = new JIFCultura();
        frame.setCultura(c);
        frame.setTitle("Editar Cultura");
        getParent().add(frame);
        frame.setVisible(true);
    }
}
