/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mau.screens;

import br.com.mau.dao.impl.GenericDAO;
import br.com.mau.model.Cultura;
import br.com.mau.model.Setor;
import br.com.mau.util.JPAUtil;
import br.com.mau.validation.SetorValidator;
import java.awt.Rectangle;
import java.util.ArrayList;
import java.util.Hashtable;
import java.util.List;
import javax.swing.JOptionPane;
import br.com.mau.controller.PersistenceController;

/**
 *
 * @author Mauricio
 */
public class JIFSetor extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFSetor
     */
    public JIFSetor() {
        initComponents();
        populateComboCulture();
        setSize(450,450);
        jbExcluir.setVisible(Boolean.FALSE);   
        validator = new SetorValidator();
        persistenceController = new PersistenceController();
        persistenceController.loadPersistenceContext();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupStaus = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        pSetor = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfComprimento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfLargura = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbCultura = new javax.swing.JComboBox();
        tfNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescricao = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        cbTipoSolo = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jlCodigo = new javax.swing.JLabel();
        jcheckStatus = new javax.swing.JCheckBox();
        jbSalvar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Setor");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/br/images/accept.png"))); // NOI18N

        pSetor.setBorder(javax.swing.BorderFactory.createTitledBorder("Setor"));

        jLabel4.setText("comprimento:");

        tfComprimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfComprimentoActionPerformed(evt);
            }
        });

        jLabel5.setText("largura:");

        tfLargura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLarguraActionPerformed(evt);
            }
        });

        jLabel3.setText("cultura:");

        cbCultura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbCulturaMouseClicked(evt);
            }
        });
        cbCultura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCulturaActionPerformed(evt);
            }
        });

        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });

        jLabel2.setText("nome:");

        jLabel1.setText("status:");

        jLabel6.setText("descrição:");

        taDescricao.setColumns(20);
        taDescricao.setRows(5);
        jScrollPane1.setViewportView(taDescricao);

        jLabel7.setText("tipo solo:");

        cbTipoSolo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Arenoso", "Argiloso", "Areno-argiloso" }));

        jLabel8.setText("codigo#:");

        jcheckStatus.setText("Ativo");

        javax.swing.GroupLayout pSetorLayout = new javax.swing.GroupLayout(pSetor);
        pSetor.setLayout(pSetorLayout);
        pSetorLayout.setHorizontalGroup(
            pSetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSetorLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(pSetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pSetorLayout.createSequentialGroup()
                        .addGroup(pSetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pSetorLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1))
                            .addGroup(pSetorLayout.createSequentialGroup()
                                .addGroup(pSetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pSetorLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(pSetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel7))
                                        .addGap(10, 10, 10)
                                        .addGroup(pSetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbCultura, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbTipoSolo, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(pSetorLayout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel1)
                                        .addGap(10, 10, 10)
                                        .addComponent(jcheckStatus)
                                        .addGap(67, 67, 67)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jlCodigo)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(pSetorLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfLargura, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );
        pSetorLayout.setVerticalGroup(
            pSetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pSetorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pSetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pSetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCultura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pSetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbTipoSolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pSetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tfLargura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(17, 17, 17)
                .addGroup(pSetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8)
                    .addComponent(jlCodigo)
                    .addComponent(jcheckStatus))
                .addGroup(pSetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pSetorLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pSetorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/images/disk.png"))); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/images/cancel.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/images/trash.png"))); // NOI18N
        jbExcluir.setText("Excluir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pSetor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jbCancelar)
                .addGap(27, 27, 27)
                .addComponent(jbExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbCancelar, jbSalvar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvar)
                    .addComponent(jbCancelar)
                    .addComponent(jbExcluir))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed

    private void tfComprimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfComprimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfComprimentoActionPerformed

    private void tfLarguraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLarguraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLarguraActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
       
        Setor s = getSetor();
       
        String msg = validator.validate(s);
        
        if(!"".equals(msg == null ? "" : msg)){
            JOptionPane.showMessageDialog(null, msg, "Validação", JOptionPane.INFORMATION_MESSAGE);
        }else{
            persistSetor(s);
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void cbCulturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCulturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCulturaActionPerformed

    private void cbCulturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbCulturaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCulturaMouseClicked

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private Setor loadSetorFromPanel(){
        String nome = null;
        
        if(!tfNome.getText().trim().isEmpty()){
            nome = tfNome.getText().trim();
        }
        
        Cultura cultura = null;
        String nomeCultura = null;
        
        nomeCultura = (String) cbCultura.getSelectedItem();
        cultura = getCulturaByName(nomeCultura);
//        cultura = (Cultura) cults.get(nomeCultura);        
        
        System.out.println(cultura.toString());
        
        String tipoSolo = (String) cbTipoSolo.getSelectedItem();
        
        Double comprimento = null;
        try{
            if(!tfComprimento.getText().trim().isEmpty()){
                   comprimento = Double.parseDouble(tfComprimento.getText().trim());
            }
        }catch(NumberFormatException e){
            throw new RuntimeException("Erro durante a conversão do campo comprimento (double).\nConteudo inválido!");
        }
        
        Double largura = null;
          try {            
            if(!tfLargura.getText().trim().isEmpty()){
                   largura = Double.parseDouble(tfLargura.getText().trim());
            }         
        } catch (NumberFormatException e) {
            throw new RuntimeException("Erro durante a conversão do campo largura (double).\nConteudo inválido!");
        }
          
        Boolean status = false;    
        
        if(jcheckStatus.isSelected()){
            status = true;
        }else {
            status = false;
        }
        
        String descricao = null;
        
        if(!taDescricao.getText().trim().isEmpty()){
            descricao = taDescricao.getText().trim();   
        }
        
        Long id = null;
        try {
            if(!jlCodigo.getText().isEmpty()) {
                id = Long.parseLong(jlCodigo.getText());
            }
        } catch (NumberFormatException e) {
            throw new RuntimeException("Erro durante a conversão do label codigo# (Long).\n");
        }
        
        return new Setor(id, largura, tipoSolo, status, comprimento, cultura, descricao, nome);
    }
    
    public void populaSetor(Setor s){        
        jlCodigo.setText(String.valueOf(s.getId()));
        tfNome.setText(s.getNome());
        taDescricao.setText(s.getDescricao());
        tfComprimento.setText(String.valueOf(s.getComprimento()));
        tfLargura.setText(String.valueOf(s.getLargura()));
        cbCultura.setSelectedItem(s.getCultura().getNome());
        cbTipoSolo.setSelectedItem(s.getTipoSolo());        
        if (s.isStatus() == Boolean.TRUE) {
            jcheckStatus.setSelected(true);            
        }
        else{
            jcheckStatus.setSelected(false);
        }
    }
    
    public void resetForm(){
        jlCodigo.setText("");
        tfNome.setText("");
        taDescricao.setText("");
        tfComprimento.setText("");
        tfLargura.setText("");
        cbCultura.setSelectedIndex(0);
        cbTipoSolo.setSelectedIndex(0);        
    }
    
    public void populateComboCulture(){
//        JComboBox combo = new JComboBox(getStoredCultures().toArray());
         storedCulturas = (ArrayList<Cultura>) getStoredCultures();
         cults = new Hashtable();
        
        for (Cultura cultura : storedCulturas) {
            cbCultura.addItem(cultura.getNome());
            cults.put(cultura.getNome(), cultura);
        }        
    }
    
    public List getStoredCultures(){        
        GenericDAO dao = new GenericDAO(JPAUtil.createEntityManager(), Cultura.class);
        return dao.findAll();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupStaus;
    private javax.swing.JComboBox cbCultura;
    private javax.swing.JComboBox cbTipoSolo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JCheckBox jcheckStatus;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JPanel pSetor;
    private javax.swing.JTextArea taDescricao;
    private javax.swing.JTextField tfComprimento;
    private javax.swing.JTextField tfLargura;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Cultura> storedCulturas;
    private Hashtable cults;
    private SetorValidator validator;
    private PersistenceController persistenceController;
    

    @Override
    public void computeVisibleRect(Rectangle visibleRect) {
        super.computeVisibleRect(visibleRect);
    }
    
    
    private Cultura getCulturaByName(String name) {
        GenericDAO dao = new GenericDAO(persistenceController.getPersistenceContext(), Cultura.class);
        
        return (Cultura)dao.findByName(name).get(0);
    }
    
    public void setSetor(Setor s){
        resetForm();
        if(s != null){
            populaSetor(s);
            jbExcluir.setVisible(Boolean.TRUE);
        }
    }
    
    public Setor getSetor(){
        return loadSetorFromPanel();
    }

    private void persistSetor(Setor s) {
         GenericDAO dao = new GenericDAO(persistenceController.getPersistenceContext(), Setor.class);
        if(s.getId() != null){
           dao.update(s);
           JOptionPane.showMessageDialog(null, "Setor Atualizado!!","Atualização",
           JOptionPane.INFORMATION_MESSAGE);        
        }else{
            dao.save(s);
            JOptionPane.showMessageDialog(null, "Cadastrado no Banco!!","Cadastro Efetuado",
            JOptionPane.INFORMATION_MESSAGE);
        }        
        dispose();
        dao.close();
    }
}
