/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mau.screens;

import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.metal.DefaultMetalTheme;
import javax.swing.plaf.metal.MetalLookAndFeel;
import javax.swing.plaf.metal.OceanTheme;

/**
 *
 * @author Mauricio
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setSize(1000, 800);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setBackgroundDesktopPane();
        jDPCadastro.setEnabled(true);
        centraliza(getAuthScreen());
        //desabilita menus
        disabledMenu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDPCadastro = new javax.swing.JDesktopPane();
        menuBarMain = new javax.swing.JMenuBar();
        menuUsuario = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuAgenda = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmenuComm = new javax.swing.JMenuItem();
        menuSetor = new javax.swing.JMenu();
        jmenuCadastrarSetor = new javax.swing.JMenuItem();
        menuCultura = new javax.swing.JMenu();
        jmenuCadastrarCultura = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        jMIMercadorias = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Cadastro");

        jDPCadastro.setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDPCadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDPCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
        );

        menuBarMain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        menuUsuario.setText("Usuario");
        menuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuarioActionPerformed(evt);
            }
        });

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/images/user.png"))); // NOI18N
        jMenuItem1.setText("Cadastro Usuarios");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuUsuario.add(jMenuItem1);

        jMenuItem3.setText("Editar Usuario");
        menuUsuario.add(jMenuItem3);

        menuBarMain.add(menuUsuario);

        menuAgenda.setText("Agenda");

        jMenuItem2.setText("Agendamento");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuAgenda.add(jMenuItem2);

        jmenuComm.setText("Communication");
        jmenuComm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuCommActionPerformed(evt);
            }
        });
        menuAgenda.add(jmenuComm);

        menuBarMain.add(menuAgenda);

        menuSetor.setText("Setor");

        jmenuCadastrarSetor.setText("Cadastrar Setor");
        jmenuCadastrarSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuCadastrarSetorActionPerformed(evt);
            }
        });
        menuSetor.add(jmenuCadastrarSetor);

        menuBarMain.add(menuSetor);

        menuCultura.setText("Cultura");

        jmenuCadastrarCultura.setText("Cadastrar Cultura");
        jmenuCadastrarCultura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuCadastrarCulturaActionPerformed(evt);
            }
        });
        menuCultura.add(jmenuCadastrarCultura);

        menuBarMain.add(menuCultura);

        menuRelatorios.setText("Relatorios");
        menuRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelatoriosActionPerformed(evt);
            }
        });

        jMIMercadorias.setText("Ambientes");
        jMIMercadorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIMercadoriasActionPerformed(evt);
            }
        });
        menuRelatorios.add(jMIMercadorias);

        menuBarMain.add(menuRelatorios);

        setJMenuBar(menuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        
        //JIFCadastro cadastro = new JIFCadastro();
        JIFUser user = new JIFUser();
        
        jDPCadastro.add(user);
        
        user.setVisible(true);
                
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuarioActionPerformed

       
        
    }//GEN-LAST:event_menuUsuarioActionPerformed

    private void jMIMercadoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIMercadoriasActionPerformed
        
//         JIFListaMercadorias mercadorias = new JIFListaMercadorias();
//        
//         jDPCadastro.add(mercadorias);
//         
//        mercadorias.setVisible(true);
        
        
        
    }//GEN-LAST:event_jMIMercadoriasActionPerformed

    private void menuRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelatoriosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuRelatoriosActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JIFAgendamento agenda = new JIFAgendamento();
        jDPCadastro.add(agenda);
        agenda.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jmenuCadastrarSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuCadastrarSetorActionPerformed
        
//        JIFSetor setor = new JIFSetor();
//        jDPCadastro.add(setor);
//        setor.setVisible(true);
        
        JIFGestaoSetor gerenciadorSetor = new JIFGestaoSetor();
        jDPCadastro.add(gerenciadorSetor);
        gerenciadorSetor.setVisible(true);
    }//GEN-LAST:event_jmenuCadastrarSetorActionPerformed

    private void jmenuCadastrarCulturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuCadastrarCulturaActionPerformed
        
//        JIFCultura cultura = new JIFCultura();
//        jDPCadastro.add(cultura);
//        cultura.setVisible(true);
        
        JIFGestao gerenciadorCultura = new JIFGestao();
        jDPCadastro.add(gerenciadorCultura);
        gerenciadorCultura.setVisible(true);
        
    }//GEN-LAST:event_jmenuCadastrarCulturaActionPerformed

    private void jmenuCommActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuCommActionPerformed
        
        JIFConnection conn = new JIFConnection();
        jDPCadastro.add(conn);
        
        conn.setVisible(true);
        
        
    }//GEN-LAST:event_jmenuCommActionPerformed

    public static void setLookAndFeelAtSystem(String lookandfeel, String Theme) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException{
        String lookAndFeel = null;
       
        if (lookandfeel != null) {
            switch (lookandfeel) {
                case "Metal":
                    lookAndFeel = UIManager.getCrossPlatformLookAndFeelClassName();
                  //  an alternative way to set the Metal L&F is to replace the 
                  // previous line with:
                  // lookAndFeel = "javax.swing.plaf.metal.MetalLookAndFeel";
                    break;
                case "System":
                    lookAndFeel = UIManager.getSystemLookAndFeelClassName();
                    break;
                case "Nimbus":
                    lookAndFeel = "com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel";
                    break;
                case "Motif":
                    lookAndFeel = "com.sun.java.swing.plaf.motif.MotifLookAndFeel";
                    break;
                case "GTK":
                    lookAndFeel = "com.sun.java.swing.plaf.gtk.GTKLookAndFeel";
                    break;
                case "Liquid":
                        lookAndFeel = "com.birosoft.liquid.LiquidLookAndFeel";
                        break;
                default:
                    System.err.println("Unexpected value of LOOKANDFEEL specified: "
                                       + lookandfeel);
                    lookAndFeel = UIManager.getCrossPlatformLookAndFeelClassName();
                    break;
            }

    }
        
            UIManager.setLookAndFeel(lookAndFeel);
            if (lookandfeel.equals("Metal")) {
                switch (Theme) {
                    case "DefaultMetal":
                        MetalLookAndFeel.setCurrentTheme(new DefaultMetalTheme());
                        break;
                    case "Ocean":
                        MetalLookAndFeel.setCurrentTheme(new OceanTheme());
                        break;
                }
                                       
                  UIManager.setLookAndFeel(new MetalLookAndFeel()); 
                }	
        
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
    //        try {
    //            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    //                if ("Nimbus".equals(info.getName())) {
    //                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
    //                    break;
    //                }
    //            }
    //        } catch (ClassNotFoundException ex) {
    //            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //        } catch (InstantiationException ex) {
    //            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //        } catch (IllegalAccessException ex) {
    //            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    //            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //        }
            //</editor-fold>
//            UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
            setLookAndFeelAtSystem("System", null);
//            setLookAndFeelAtSystem("Metal", "");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDPCadastro;
    private javax.swing.JMenuItem jMIMercadorias;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jmenuCadastrarCultura;
    private javax.swing.JMenuItem jmenuCadastrarSetor;
    private javax.swing.JMenuItem jmenuComm;
    private javax.swing.JMenu menuAgenda;
    private javax.swing.JMenuBar menuBarMain;
    private javax.swing.JMenu menuCultura;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenu menuSetor;
    private javax.swing.JMenu menuUsuario;
    // End of variables declaration//GEN-END:variables
    
    
    private void setBackgroundDesktopPane() {
        
        JLabel label = new JLabel(new ImageIcon(getClass().getResource("/br/images/jardins.jpg")));
        
        double altura = Toolkit.getDefaultToolkit().getScreenSize().getHeight();
        double largura = Toolkit.getDefaultToolkit().getScreenSize().getWidth();
        
        int alt  = (int) altura;
        int larg  = (int) largura;
        
        label.setBounds(0,0, larg,alt);
               
        jDPCadastro.add(label);
    }

    private JInternalFrame getAuthScreen() {
        JIFAuth auth = new JIFAuth();
        jDPCadastro.add(auth);        
        auth.setVisible(true);        
        return auth;
    }

    private void centraliza(JInternalFrame janela) {
        int alturaPrincipal = (int)Toolkit.getDefaultToolkit().getScreenSize().getHeight();
        int larguraPrincipal =(int)Toolkit.getDefaultToolkit().getScreenSize().getWidth();
        
        int lIFrame = janela.getWidth();    
        int aIFrame = janela.getHeight();    
        
        janela.setLocation((larguraPrincipal/2) - lIFrame/2 ,alturaPrincipal/2 - aIFrame/2);
        
        janela.setVisible(true);
        
        
        //System.out.println("largura: "+larguraPrincipal+" Altura "+alturaPrincipal + "LargInternal: "+lIFrame+" AlturaInternal "+aIFrame);
    }

    public void disabledMenu() {
        if(menuBarMain.isEnabled()){
            menuUsuario.setEnabled(false);
            menuAgenda.setEnabled(false);
            menuCultura.setEnabled(false);
            menuSetor.setEnabled(false);
            menuRelatorios.setEnabled(false);
        }
    }
}
